LANGUAGES = {
    'uzbek' : {
        'buttons':{
            'btn_today':'⏰ Bugungi',
            'btn_tomorrow':'⏳ Ertangi',
            'btn_week':'📆 Haftalig',
            'btn_set_loc':"⚙️ Joylashuvni o'zgartirish",
            'btn_set_lan':"🇺🇿 Tilni o'zgartirish",
            'btn_statistics':'📊 Statistika',
            'btn_location':"📍 Joylashuv bo'yicha",
            'btn_back':'🔙 Orqaga',
            },
        'texts':{
            'reg_choose':'Viloyatingizni tanlang',
            'dis_choose':'Tumaningizni tanlang',
            'dis_chosen':" tumanini tanladingiz ma'lumotingiz saqlandi!",
            'edit_settings':" siz ma'lumotlaringizni qayta kiritishni tanladingiz",    
            'message_lang' : "Tilni o'zgartirishni tanladingiz",
            'all_users' : '👥 Barcha foydalanuvchilar',
            'active_users' : '👨🏻‍💻 Aktive foydalanuvchilar',
            'today_users' : "🫂 Bugun qo'shilganlar",
            'smt' : "<b>Ertangi kungi namoz vaqtlari</b>", 
        },
        'pray_names' :{
            "Fajr":   "Tong", 
            'Sunrise':"Quyosh ⬆️",
            "Dhuhr":  "Peshin", 
            "Asr":    "Asr", 
            "Sunset": "Quyosh ⬇️",
            "Maghrib":"Shom", 
            "Isha":   "Hufton", 
            "Midnight":"Yarim tun"
        },
                
        'day_names': {
            0 : "Dushanba",
            1 : "Seshanba",
            2 : "Chorshanba",
            3 : "Payshanba",
            4 : "Juma",
            5 : "Shanba",
            6 : "Yakshanba",
        },
        'month_names':{
            1 : "Yanvar",
            2 : "Fevral",
            3 : "Mart",
            4 : "Aprel",
            5 : "May",
            6 : "Iyun",
            7 : "Iyul",
            8 : "Avgust",
            9 : "Sentyabr",
            10 : "Oktyabr",
            11 : "Noyabr",
            12 : "Dekabr",
        },
    },
    'kril' :{
        'buttons':{
            'btn_today':'⏰ Бугунги',
            'btn_tomorrow':'⏳ Эртанги',
            'btn_week':'📆 Ҳафталиг',
            'btn_set_loc':"⚙️ Жойлашувни ўзгартириш",
            'btn_set_lan':"🇺🇿 Тилни ўзгартириш",
            'btn_statistics':'📊 Статистика',
            'btn_location':"📍 Жойлашув бўйича",
            'btn_back':'🔙 Орқага',
            }, 
        'texts':{
            'reg_choose':'Вилоятингизни танланг',
            'dis_choose':'Туманингизни танланг',
            'dis_chosen':' туманини танладингиз маълумотингиз сақланди!',
            'edit_settings':" сиз маълумотларингизни қайта киритишни танладингиз.",
            'message_lang' : 'Тилни ўзгартиришни танладингиз',
            'all_users' : '👥 Барча фойдаланувчилар',
            'active_users' : '👨🏻‍💻 Актив фойдаланувчилар',
            'today_users' : "🫂 Бугун қўшилганлар",  
            'smt' : "<b>Эртанги кун учун намоз вақтлари</b>",  
        },
        'pray_names' :{
            "Fajr":    "Тонг", 
            'Sunrise': "Қуёш ⬆️",
            "Dhuhr":   "Пешин", 
            "Asr":     "Аср", 
            "Sunset":  "Қуёш ⬇️",
            "Maghrib": "Шом", 
            "Isha":    "Хуфтон", 
            "Midnight":"Ярим тун"
        },
                
        'day_names': {
            0 : "Душанба",
            1 : "Сешанба",
            2 : "Чоршанба",
            3 : "Пайшанба",
            4 : "Жума",
            5 : "Шанба",
            6 : "Якшанба",
        },
        'month_names':{
            1 : "Январ",
            2 : "Феврал",
            3 : "Март",
            4 : "Апрел",
            5 : "Май",
            6 : "Июн",
            7 : "Июл",
            8 : "Август",
            9 : "Сентябр",
            10 : "Октябр",
            11 : "Ноябр",
            12 : "Декабр",
        },
    }
}